---
- name: Get packagecloud erlang repository
  get_url:
    url: "{{ erlang_yum_repository_url }}"
    dest: "{{ erlang_yum_repository_path }}"
    force: yes

- name: Get packagecloud rabbitmq repository
  get_url:
    url: "{{ rabbitmq_yum_repository_url }}"
    dest: "{{ rabbitmq_yum_repository_path }}"
    force: yes

- name: Add packagecloud GPG key.
  rpm_key:
    key: "https://packagecloud.io/gpg.key"
    state: present

- name: Ensure RabbitMQ is installed.
  yum:
    name: "{{ rabbitmq_basename }}-{{ rabbitmq_version }}"
    state: "present"
    disablerepo: "epel"
    enablerepo:
      - rabbitmq_erlang
      - rabbitmq_rabbitmq-server
